APP-5811: [Android] Create SDK for Checkout
paysera/kotlin-lib-checkout-sdk pull request #1
Opened 2023-07-07 08:48 UTC by AndriiSerheniuk

2023-07-11 06:47 UTC, gilbertparreno requested changes

2023-07-11 06:47 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/entities/PaymentTypeResponse.kt
> +    data class PaymentType(
Can we create a separate class for this one and named it **PSPaymentType**?

2023-07-11 06:47 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/retrofit/NetworkApiClient.kt
> +    @GET("payment-url/{paymentTypeId}")
We're using PaymentType.key here so I think we can rename `paymentTypeId` to `paymentTypeKey` instead?

2023-07-11 06:47 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/retrofit/NetworkApiClient.kt
> +        @Path("paymentTypeId") paymentTypeId: String,
Same on this one.

2023-07-11 06:47 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/retrofit/NetworkApiClient.kt
> +        @Query("lang") lang: String
```suggestion
       @Query("lang") locale: String
```

2023-07-11 06:47 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/clients/CheckoutApiClient.kt
> +        lang: String
Can we wrap this fields inside a class?

2023-07-11 06:50 UTC, gilbertparreno commented
Also can we add unit tests for this new SDK?

2023-07-13 04:00 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/clients/CheckoutApiClient.kt
> +        lang: String
Still not fixed.

2023-07-13 04:01 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/entities/PaymentUrl.kt
> +data class PaymentUrl(val paymentUrl: String)
**PaymentUrl** -> **PSPaymentUrl**

2023-07-13 06:24 UTC, AndriiSerheniuk commented on src/main/kotlin/com/paysera/lib/checkout/entities/PaymentUrl.kt
> +data class PaymentUrl(val paymentUrl: String)
btw why PS? because **P**ay**S**era?

2023-07-13 06:30 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/entities/PaymentUrl.kt
> +data class PaymentUrl(val paymentUrl: String)
We used this prefix in InRento, @eunicegalang shall we still used this `PS` to match with inrento sdk?

2023-07-14 01:54 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/checkout/entities/SPPaymentUrlRequest.kt
> +data class SPPaymentUrlRequest(
PS?

2023-07-14 06:05 UTC, eunicegalang commented on src/main/kotlin/com/paysera/lib/checkout/entities/PaymentUrl.kt
> +data class PaymentUrl(val paymentUrl: String)
Yes

2023-07-14 07:41 UTC, gilbertparreno approved these changes

2023-07-16 17:52 UTC, s-k-georgiev commented on src/main/kotlin/com/paysera/lib/checkout/retrofit/NetworkApiFactory.kt
> +    baseUrl: String,
@gilbertparreno Do we need `locale` parameter, as with our other SDKs?

2023-07-16 18:45 UTC, s-k-georgiev commented on src/main/kotlin/com/paysera/lib/checkout/retrofit/NetworkApiClient.kt
> +        @Path("paymentTypeKey") paymentTypeKey: String,
Do we pass key or id, because on backend side it is named `paymentTypeId`

2023-07-17 10:50 UTC, s-k-georgiev approved these changes

2023-07-17 11:56 UTC, merged